### ISSUE TITLE
Week 1 Assignment: Review My App

### ISSUE THREAD

**Issue by bluyam** [bluyam/flicks#1]
My app contains all the required features (and I'll try to add more optionals by the end of the day), and it's ready for review! /cc @codepathreview

**Comment by codepathreview** [comment]
Hi @bluyam, I cannot build your app because you imported an image from you computer directly. So it cannot be found in my computer.
<img width="417" alt="screen shot 2016-01-26 at 10 51 22 pm" src="https://cloud.githubusercontent.com/assets/7917093/12585672/9f7971ea-c47f-11e5-9868-184902e655b7.png">

<img width="224" alt="screen shot 2016-01-26 at 10 51 32 pm" src="https://cloud.githubusercontent.com/assets/7917093/12585673/a1933c0e-c47f-11e5-92fb-af1704590ee9.png">

Please add all of your images to `Assets.xcassets` folder.

Could you fix it asap and let me know when you complete?

**Comment by bluyam** [comment]
Sorry for the wait! Everything should be good to go now @codepathreview

**Comment by codepathreview** [comment]
:+1: Nice work! The point of this homework was to get a chance to implement a TableView (one of the most common views in iOS) and to work with real data over the network (in this case from the Movies Database API).

A key part of these projects is that you add additional features and tweak the UI / UX because that will provide the most learning opportunities. We encourage you to complete the projects early each week with the required stories and then spend time adding your own UI elements and experimenting with optional extensions that will improve the user experience.

### Some small comments:
- Please be sure to follow the Swift code styling conventions for the homework .
  - Here is the useful guide: [Ray Wenderlich Swift Style Guide](https://github.com/raywenderlich/swift-style-guide)
- Well done with using `UICollectionView` instead of `UITableView` to display movies. I don't know why your app looks different from your GIF file but I did love the old UI. It's very impressive :sparkler: 
- Good job using `TabBar` to show 2 lists of movies. Another way to implement this feature is adding `Tab Bar` (not `Tab Bar Controller`) from the `Interface Builder`. It could be easier :smile:
- Good job using `if let` to unwrap variables.
- You can initialize `movies` when declare like this `var movies = [NSDictionary]()` so you can use it anywhere without unwrapping. By this way, the function `numberOfItemsInSection` will be simpler, just use `return movies.count`.

Good submission overall! :star:

We have a detailed [Project 1 Feedback Guide](http://courses.codepath.com/snippets/ios_university/feedback_guides/project_1_feedback.md) which covers the best practices for implementing this assignment. Read through the feedback guide point-by-point to determine ways you might be able to improve your submission. You should consider going back and implementing these improvements as well. Keep in mind that one of the most important parts of iOS development is learning the correct patterns and conventions.

If you have any particular questions about the assignment or the feedback, feel free to reply here or email us at universitysupport@codepath.com.
